---
- name: Configure interface on Cisco ASA device
  hosts: asa_devices
  gather_facts: no
  tasks:
    - name: Configure GigabitEthernet0/1 with IP address
      asa_config:
        lines:
          - interface GigabitEthernet0/1
          - ip address 192.168.3.1 255.255.255.0

