---
- name: Configure hostname on Juniper device
  hosts: juniper_devices
  gather_facts: no
  tasks:
    - name: Configure hostname
      junos_config:
        lines:
          - set system host-name {{ inventory_hostname }}

